version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/angular"
    schedule:
      interval: "daily"
