version: '3'
services:
  db:
    image: postgres:12.4
    environment:
      POSTGRES_DB: ccf
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
  backend:
    build:
      context: java/backend
      dockerfile: Dockerfile
    environment:
      IDAM_URI: http://idam-api:5000
    command:
      - --generate-data=true
    depends_on:
      - db
    expose:
      - 8080

