version: '3'
services:
  db:
    ports:
      - "5432:5432"
  backend:
    ports:
      - "8080:8080"
    volumes:
      - './java/build/libs:/app'
  frontend:
    ports:
      - "4200:4200"
      # Debugging port
      - "9222:9222"
    volumes:
      - './angular:/app'
      - 'node_modules:/app/node_modules'
  keycloak:
    ports:
      - "8090:8080"

volumes:
  node_modules:
