version: '3'
services:
  db:
    image: postgres:12.4
    environment:
      POSTGRES_DB: ccf
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
  backend:
    build:
      context: java
      dockerfile: Dockerfile
    environment:
      IDAM_URI: http://keycloak:8080/auth/realms/rse
    command:
      - --generate-data=true
    depends_on:
      - db
      - keycloak
    ports:
      - "8080:8080"
    volumes:
      - './java/build/libs:/app'
  frontend:
    build:
      context: angular
      dockerfile: Dockerfile
    command: ${NG_COMMAND}
    depends_on:
      - backend
    ports:
      - "4200:4200"
      # Debugging port
      - "9222:9222"
    volumes:
      - './angular:/app'
      - 'node_modules:/app/node_modules'
  keycloak:
    build:
      context: keycloak
      dockerfile: Dockerfile
    ports:
      - "8090:8080"

volumes:
  node_modules:
