version: '3'
services:
  db:
    image: postgres:12.4
    environment:
      POSTGRES_DB: ccf
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
  backend:
    build:
      context: java/backend
      dockerfile: Dockerfile
    environment:
      IDAM_URI: http://keycloak:8080/auth/realms/rse
    command:
      - --generate-data=true
    depends_on:
      - db
      - keycloak
    expose:
      - 8080

  keycloak:
    build:
      context: keycloak
      dockerfile: Dockerfile
    expose:
      - 8090
